name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment: 
      name: production
    permissions:
      contents: write
    steps:
      - name: base
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/base.svg
          base: header, activity, repositories
          base_hireable: yes
          repositories_forks: yes
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Europe/Moscow
      - name: WakaTime
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: time, projects, projects-graphs, languages, languages-graphs, editors, os
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
